### ISSUE TITLE
Product support cards

### ISSUE THREAD

**Issue by krizel4** [hlxsites/mammotome#293] opened 2023-06-19 20:24 UTC
Product support cards and header are overlapping at the top in mobile. ![image](https://github.com/hlxsites/mammotome/assets/55035633/72366d3c-b08f-4430-93a6-9cebff3d78cc)

**Comment by Acidham** [comment] 2023-06-20 12:55
Duplicate of #277

**Comment by meryllblanchet** [comment] 2023-06-21 06:55
Closing in favor of #277

**Closed by meryllblanchet** 2023-06-21 06:55 UTC
Labels: duplicate
